# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: andeveling
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-ecommerce-products-crud


provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:sa-east-1:531334400435:table/ProductsDynamoDbTable"
  deploymentBucket:
    name: serverless-andres-test 
  

functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get
  
  addProduct:
    handler: src/addProduct.addProduct
    events:
      - httpApi:
          path: /products
          method: post


resources:
  Resources:
    ProductsDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductsDynamoDbTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
